EasyMealCookGUI/Models/ViewModels/DishViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EasyMealCookGUI.Models.ViewModels
{
	public class DishViewModel
	{
		public Boolean Starter { get; set; }

		[Required(ErrorMessage = "Please specify if meal is main dish")]
		public Boolean MainDish { get; set; }

		[Required(ErrorMessage = "Please specify if meal is dessert")]
		public Boolean Dessert { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains salt")]
		public Boolean Salt { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains diabetes ")]
		public Boolean Diabetes { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains glutes")]
		public Boolean Glutes { get; set; }

		[Required(ErrorMessage = "Please specify a name")]
		public String Name { get; set; }

		[Required(ErrorMessage = "Please specify a description")]
		public String Description { get; set; }

		[Required]
		[Column(TypeName = "decimal(18,2)")]
		[Range(0.01, double.MaxValue,
		ErrorMessage = "Please enter a positive price")]
		public decimal Price { get; set; }

		public IFormFile Image { get; set; }

	}
}

EasyMealCookGUI/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EasyMealCookGUI.Models.ViewModels;
using EasyMealCore.DomainModel;
using EasyMealCore.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EasyMealCookGUI.Controllers
{
    public class DishController : Controller
    {

		private IPlanningRepository repository;

		public DishController(IPlanningRepository repo)
		{
			repository = repo;
		}
		public IActionResult Create()
        {
            return View();
        }

		[HttpPost]
		[Authorize]
		public IActionResult CreateDish(DishViewModel data)
		{
			Console.WriteLine(data);

			Dish dish = new Dish
			{
				Name = data.Name,
				Description = data.Description,
				Price = data.Price,
				Starter = data.Starter,
				MainDish = data.MainDish,
				Dessert = data.Dessert,
				Salt = data.Salt,
				Glutes = data.Glutes,
				Diabetes = data.Diabetes,
			};

			{
				using (var ms = new MemoryStream())
				{
					data.Image.CopyTo(ms);
					dish.Image = ms.ToArray();
				}
			}
		
			repository.SaveDish(dish);
			TempData["message"] = $"{dish.Name} is opgeslagen";
			return RedirectToAction("Index","Home");
		}
	}
}

EasyMealCookGUI/Views/Dish/Create.cshtml
@model DishViewModel
@{
    ViewData["Title"] = "Create";
}
<div class="container login-container mt-md-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form asp-action="CreateDish" asp-controller="Dish" enctype="multipart/form-data" method="post">
                <div class="form-group">
                    <div><span asp-validation-for="Name" class="text-danger"></span></div>
                    <label>Name</label>
                    <input type="text" class="form-control" placeholder="Name for the dish *" asp-for="Name" />
                </div>
                <div class="form-group">
                    <div><span asp-validation-for="Description" class="text-danger"></span></div>
                    <label>Description</label>
                    <input type="text" class="form-control" placeholder="Description for the dish *" asp-for="Description" />
                </div>
                <div class="form-group">
                    <div><span asp-validation-for="Price" class="text-danger"></span></div>
                    <label>Price</label>
                    <input type="text" class="form-control" placeholder="€10,00 *" asp-for="Price" />
                </div>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-sm-5 pt-0">Course:</legend>
                        <div class="col-sm-7">
                            <div class="form-check">
                                <div><span asp-validation-for="Starter" class="text-danger"></span></div>
                                <input class="form-check-input" type="checkbox" id="Starter" asp-for="Starter">
                                <label class="form-check-label">
                                    Starter
                                </label>
                            </div>
                            <div class="form-check">
                                <div><span asp-validation-for="MainDish" class="text-danger"></span></div>
                                <input class="form-check-input" type="checkbox" id="MainDish" asp-for="MainDish">
                                <label class="form-check-label">
                                    Main
                                </label>
                            </div>
                            <div class="form-check">
                                <div><span asp-validation-for="Dessert" class="text-danger"></span></div>
                                <input class="form-check-input" type="checkbox" id="Dessert" asp-for="Dessert">
                                <label class="form-check-label">
                                    Dessert
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-sm-5 pt-0">Restrictions:</legend>
                        <div class="col-sm-7">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" asp-for="Glutes">
                                <label class="form-check-label">
                                    Contains glutes
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" asp-for="Salt">
                                <label class="form-check-label">
                                    Contains salt
                                </label>
                            </div>
                            <div class="form-check disabled">
                                <input class="form-check-input" type="checkbox" asp-for="Diabetes">
                                <label class="form-check-label">
                                    Diabetes
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" accept="image/x-png,image/gif,image/jpeg, image/jpg" class="custom-file-input" id="customFile" asp-for="Image">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                </div>
                <div class="text-center mt-3">
                    <button class="btn btn-primary" type="submit">Save</button>
                    <a asp-action="Index" asp-controller="home" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>