EasyMealCookGUI/Models/ViewModels/DishViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EasyMealCookGUI.Models.ViewModels
{
	public class DishViewModel
	{
		public Boolean Starter { get; set; }

		[Required(ErrorMessage = "Please specify if meal is main dish")]
		public Boolean MainDish { get; set; }

		[Required(ErrorMessage = "Please specify if meal is dessert")]
		public Boolean Dessert { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains salt")]
		public Boolean Salt { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains diabetes ")]
		public Boolean Diabetes { get; set; }

		[Required(ErrorMessage = "Please specify if meal contains glutes")]
		public Boolean Glutes { get; set; }

		[Required(ErrorMessage = "Please specify a name")]
		public String Name { get; set; }

		[Required(ErrorMessage = "Please specify a description")]
		public String Description { get; set; }

		[Required]
		[Column(TypeName = "decimal(18,2)")]
		[Range(0.01, double.MaxValue,
		ErrorMessage = "Please enter a positive price")]
		public decimal Price { get; set; }

		public IFormFile Image { get; set; }

	}
}

EasyMealCookGUI/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EasyMealCore.DomainServices;
using Microsoft.AspNetCore.Authorization;
using EasyMealCore.DomainModel;

namespace EasyMealCookGUI.Controllers
{
	[Authorize]
	public class CardController : Controller
    {
		private IPlanningRepository repository;

		public CardController(IPlanningRepository repo)
		{
			repository = repo;
		}

		
		public IActionResult Import()
		{
			return View("Import",repository.Dishes);
		}

		[Authorize]
		public IActionResult add(int DishId)
		{
			Dish dish = repository.Dishes.FirstOrDefault(d =>
		   d.DishId == DishId);

			if(dish != null)
			{
				repository.SaveDish(dish);
				TempData["message"] = $"{dish.Name} is selecteerbaar";
			
			}
			return RedirectToAction("Import");
		}
		[Authorize]
		public IActionResult remove(int DishId)
		{
			Dish dish = repository.Dishes.FirstOrDefault(d =>
			d.DishId == DishId);

			if (dish != null)
			{
				repository.SaveDish(dish);
				TempData["message"] = $"{dish.Name} is niet meer selecteerbaar";
				
			}
			return RedirectToAction("Import");
		}

		
		public ViewResult Create() => View("Create", new Dish());

	}
}

EasyMealCookGUI/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EasyMealCookGUI.Models.ViewModels;
using EasyMealCore.DomainModel;
using EasyMealCore.DomainServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EasyMealCookGUI.Controllers
{
    public class DishController : Controller
    {

		private IPlanningRepository repository;

		public DishController(IPlanningRepository repo)
		{
			repository = repo;
		}
		public IActionResult Create()
        {
            return View();
        }

		[HttpPost]
		[Authorize]
		public IActionResult CreateDish(DishViewModel data)
		{
			Console.WriteLine(data);

			Dish dish = new Dish
			{
				Name = data.Name,
				Description = data.Description,
				Price = data.Price,
				Starter = data.Starter,
				MainDish = data.MainDish,
				Dessert = data.Dessert,
				Salt = data.Salt,
				Glutes = data.Glutes,
				Diabetes = data.Diabetes,
			};

			{
				using (var ms = new MemoryStream())
				{
					data.Image.CopyTo(ms);
					dish.Image = ms.ToArray();
				}
			}
		
			repository.SaveDish(dish);
			TempData["message"] = $"{dish.Name} is opgeslagen";
			return RedirectToAction("Index","Home");
		}
	}
}

EasyMealCookGUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/css/StyleSheet.css" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="/">Easymeal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Settings
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log out</a>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/js/JavaScript.js"></script>
</body>
</html>

EasyMealCookGUI/Views/Shared/dish.cshtml
@model EasyMealCore.DomainModel.Dish

<div class="meal">
    <img class="mealImage" src="~/Images/soep-van-tomaten-en-puntpaprikas_4.jpg" />
    <div class="information">
        <h3 class="title">@Model.Name</h3>
        <p class="description">@Model.Description</p>
    </div>
    <div class="price">
        <h4>@Model.Price.ToString("c")</h4>
    </div>
    @*@if (Model.Active)
    {
        <form asp-action="remove" asp-controller="Card">
            <input type="hidden" name="DishId" value="@Model.DishId" />
            <button type="submit" class="btn btn-sm btn-danger">remove</button>
        </form>
    }
    else
    { <form asp-action="add" asp-controller="Card">
            <input type="hidden" name="DishId" value="@Model.DishId" />
            <button type="submit" class="btn btn-sm btn-danger">add</button>
        </form>
    }*@
</div>

<br />
<hr class="mealSeparator" />

EasyMealCookGUI/Views/Shared/dishOverview.cshtml
@using EasyMealCore.DomainModel
@model IEnumerable<EasyMealCore.DomainModel.Dish>
@{
    ViewData["Title"] = "dishOverview";
}

    @foreach (Dish d in Model)
    {
        <p>@d.Name</p>
        <br />
    }